const useCountries = (code) =>{
if (code == 'AF') {return 'Afganistán'
} else if (code == 'AL') {return 'Albania'
} else if (code == 'DZ') {return 'Argelia'
} else if (code == 'AS') {return 'Samoa Americana'
} else if (code == 'AD') {return 'Andorra'
} else if (code == 'AO') {return 'Angola'
} else if (code == 'AI') {return 'Anguilla'
} else if (code == 'AQ') {return 'Antártida'
} else if (code == 'AG') {return 'Antigua y Barbuda'
} else if (code == 'AR') {return 'Argentina'
} else if (code == 'AM') {return 'Armenia'
} else if (code == 'AW') {return 'Aruba'
} else if (code == 'AU') {return 'Australia'
} else if (code == 'AT') {return 'Austria'
} else if (code == 'AZ') {return 'Azerbaiyán'
} else if (code == 'BS') {return 'Bahamas'
} else if (code == 'BH') {return 'Baréin'
} else if (code == 'BD') {return 'Banglades'
} else if (code == 'BB') {return 'Barbados'
} else if (code == 'BY') {return 'Bielorrusia'
} else if (code == 'BE') {return 'Bélgica'
} else if (code == 'BZ') {return 'Belice'
} else if (code == 'BJ') {return 'Benin'
} else if (code == 'BM') {return 'Bermudas'
} else if (code == 'BT') {return 'Butan'
} else if (code == 'BO') {return 'Bolivia'
} else if (code == 'BA') {return 'Bosnia-Herzegovina'
} else if (code == 'BW') {return 'Botsuana'
} else if (code == 'BR') {return 'Brasil'
} else if (code == 'IO') {return 'Territorio Británico del Océano Índico'
} else if (code == 'BN') {return 'Brunei'
} else if (code == 'BG') {return 'Bulgaria'
} else if (code == 'BF') {return 'Burkina Faso'
} else if (code == 'BI') {return 'Burundi'
} else if (code == 'KH') {return 'Camboya'
} else if (code == 'CM') {return 'Camerún'
} else if (code == 'CA') {return 'Canadá'
} else if (code == 'CV') {return 'Cabo Verde'
} else if (code == 'KY') {return 'Islas Caimán'
} else if (code == 'CF') {return 'República Centroafricana'
} else if (code == 'TD') {return 'Chad'
} else if (code == 'CL') {return 'Chile'
} else if (code == 'CN') {return 'China'
} else if (code == 'CX') {return 'Isla de Navidad'
} else if (code == 'CC') {return 'Islas Cocos'
} else if (code == 'CO') {return 'Colombia'
} else if (code == 'KM') {return 'Comoras'
} else if (code == 'CG') {return 'Congo'
} else if (code == 'CD') {return 'República Democrática del Congo'
} else if (code == 'CK') {return 'Islas Cook'
} else if (code == 'CR') {return 'Costa Rica'
} else if (code == 'CI') {return 'Costa de Marfil'
} else if (code == 'HR') {return 'Croacia'
} else if (code == 'CU') {return 'Cuba'
} else if (code == 'CY') {return 'Chipre'
} else if (code == 'CZ') {return 'Chequia'
} else if (code == 'DK') {return 'Dinamarca'
} else if (code == 'DJ') {return 'Yibuti'
} else if (code == 'DM') {return 'Dominica'
} else if (code == 'DO') {return 'República Dominicana'
} else if (code == 'EC') {return 'Ecuador'
} else if (code == 'EG') {return 'Egipto'
} else if (code == 'SV') {return 'El Salvador'
} else if (code == 'GQ') {return 'Guinea Ecuatorial'
} else if (code == 'ER') {return 'Eritrea'
} else if (code == 'EE') {return 'Estonia'
} else if (code == 'ET') {return 'Etiopía'
} else if (code == 'FK') {return 'Islas Malvinas'
} else if (code == 'FO') {return 'Islas Feroe'
} else if (code == 'FJ') {return 'Fiyi'
} else if (code == 'FI') {return 'Finlandia'
} else if (code == 'FR') {return 'Francia'
} else if (code == 'GF') {return 'Guayana Francesa'
} else if (code == 'PF') {return 'Polinesia Francesa'
} else if (code == 'GA') {return 'Gabón'
} else if (code == 'GM') {return 'Gambia'
} else if (code == 'GE') {return 'Georgia'
} else if (code == 'DE') {return 'Alemania'
} else if (code == 'GH') {return 'Ghana'
} else if (code == 'GI') {return 'Gibraltar'
} else if (code == 'GR') {return 'Grecia'
} else if (code == 'GL') {return 'Groenlandia'
} else if (code == 'GD') {return 'Granada'
} else if (code == 'GP') {return 'Guadalupe'
} else if (code == 'GU') {return 'Guam'
} else if (code == 'GT') {return 'Guatemala'
} else if (code == 'GG') {return 'Guernsey'
} else if (code == 'GN') {return 'Guinea'
} else if (code == 'GW') {return 'Guinea-Bisau'
} else if (code == 'GY') {return 'Guyana'
} else if (code == 'HT') {return 'Haití'
} else if (code == 'VA') {return 'Ciudad del Vaticano'
} else if (code == 'HN') {return 'Honduras'
} else if (code == 'HK') {return 'Hong Kong'
} else if (code == 'HU') {return 'Hungría'
} else if (code == 'IS') {return 'Islandia'
} else if (code == 'IN') {return 'India'
} else if (code == 'ID') {return 'Indonesia'
} else if (code == 'IR') {return 'Irán'
} else if (code == 'IQ') {return 'Iraq'
} else if (code == 'IE') {return 'Irlanda'
} else if (code == 'IM') {return 'Isla de Man'
} else if (code == 'IL') {return 'Israel'
} else if (code == 'IT') {return 'Italia'
} else if (code == 'JM') {return 'Jamaica'
} else if (code == 'JP') {return 'Japón'
} else if (code == 'JE') {return 'Jersey'
} else if (code == 'JO') {return 'Jordania'
} else if (code == 'KZ') {return 'Kazajistán'
} else if (code == 'KE') {return 'Kenia'
} else if (code == 'KI') {return 'Kiribati'
} else if (code == 'KP') {return 'Corea del Norte'
} else if (code == 'KR') {return 'Corea del Sur'
} else if (code == 'XK') {return 'Kosovo'
} else if (code == 'KW') {return 'Kuwait'
} else if (code == 'KG') {return 'Kirguistán'
} else if (code == 'LA') {return 'Laos'
} else if (code == 'LV') {return 'Letonia'
} else if (code == 'LB') {return 'Líbano'
} else if (code == 'LS') {return 'Lesoto'
} else if (code == 'LR') {return 'Liberia'
} else if (code == 'LY') {return 'Libia'
} else if (code == 'LI') {return 'Liechtenstein'
} else if (code == 'LT') {return 'Lituania'
} else if (code == 'LU') {return 'Luxemburgo'
} else if (code == 'MO') {return 'Macao'
} else if (code == 'MK') {return 'República de Macedonia'
} else if (code == 'MG') {return 'Madagascar'
} else if (code == 'MW') {return 'Malaui'
} else if (code == 'MY') {return 'Malasia'
} else if (code == 'MV') {return 'Maldivas'
} else if (code == 'ML') {return 'Malí'
} else if (code == 'MT') {return 'Malta'
} else if (code == 'MH') {return 'Islas Marshall'
} else if (code == 'MQ') {return 'Martinica'
} else if (code == 'MR') {return 'Mauritania'
} else if (code == 'MU') {return 'Mauricio'
} else if (code == 'YT') {return 'Mayotte'
} else if (code == 'MX') {return 'México'
} else if (code == 'FM') {return 'Estados Federados de Micronesia'
} else if (code == 'MD') {return 'Moldavia'
} else if (code == 'MC') {return 'Monaco'
} else if (code == 'MN') {return 'Mongolia'
} else if (code == 'ME') {return 'Montenegro'
} else if (code == 'MS') {return 'Montserrat'
} else if (code == 'MA') {return 'Marruecos'
} else if (code == 'MZ') {return 'Mozambique'
} else if (code == 'MM') {return 'Birmania'
} else if (code == 'NA') {return 'Namibia'
} else if (code == 'NR') {return 'Nauru'
} else if (code == 'NP') {return 'Nepal'
} else if (code == 'NL') {return 'Holanda'
} else if (code == 'AN') {return 'Antillas Holandesas'
} else if (code == 'NC') {return 'Nueva Caledonia'
} else if (code == 'NZ') {return 'Nueva Zelanda'
} else if (code == 'NI') {return 'Nicaragua'
} else if (code == 'NE') {return 'Niger'
} else if (code == 'NG') {return 'Nigeria'
} else if (code == 'NU') {return 'Niue'
} else if (code == 'NF') {return 'IslaNorfolk'
} else if (code == 'MP') {return 'IslasMarianasdelNorte'
} else if (code == 'NO') {return 'Noruega'
} else if (code == 'OM') {return 'Omán'
} else if (code == 'PK') {return 'Pakistán'
} else if (code == 'PW') {return 'Palaos'
} else if (code == 'PA') {return 'Panamá'
} else if (code == 'PG') {return 'Papúa Nueva Guinea'
} else if (code == 'PY') {return 'Paraguay'
} else if (code == 'PE') {return 'Perú'
} else if (code == 'PH') {return 'Filipinas'
} else if (code == 'PN') {return 'Islas Pitcairn'
} else if (code == 'PL') {return 'Polonia'
} else if (code == 'PT') {return 'Portugal'
} else if (code == 'PR') {return 'Puerto Rico'
} else if (code == 'QA') {return 'Qatar'
} else if (code == 'RO') {return 'Rumania'
} else if (code == 'RU') {return 'Rusia'
} else if (code == 'RW') {return 'Ruanda'
} else if (code == 'RE') {return 'Reunion'
} else if (code == 'BL') {return 'San Bartolome'
} else if (code == 'SH') {return 'Santa Elena, Ascensión y Tristán de Acuña'
} else if (code == 'KN') {return 'San Cristóbal y Nieves'
} else if (code == 'LC') {return 'Santa Lucía'
} else if (code == 'MF') {return 'Isla de San Martín'
} else if (code == 'PM') {return 'San Pedro y Miquelon'
} else if (code == 'VC') {return 'San Vicente y las Granadinas'
} else if (code == 'WS') {return 'Samoa'
} else if (code == 'SM') {return 'San Marino'
} else if (code == 'ST') {return ' Santo Tomé y Príncipe'
} else if (code == 'SA') {return 'Arabia Saudita'
} else if (code == 'SN') {return 'Senegal'
} else if (code == 'RS') {return 'Serbia'
} else if (code == 'SC') {return 'Seychelles'
} else if (code == 'SL') {return 'Sierra Leona'
} else if (code == 'SG') {return 'Singapur'
} else if (code == 'SK') {return 'Eslovaquia'
} else if (code == 'SI') {return 'Eslovenia'
} else if (code == 'SB') {return 'Islas Salomón'
} else if (code == 'SO') {return 'Somalia'
} else if (code == 'ZA') {return 'Sudáfrica'
} else if (code == 'SS') {return 'Sudán del Sur'
} else if (code == 'ES') {return 'España'
} else if (code == 'LK') {return 'Sri Lanka'
} else if (code == 'PS') {return 'Estado de Palestina'
} else if (code == 'SD') {return 'Sudán'
} else if (code == 'SR') {return 'Surinam'
} else if (code == 'SJ') {return 'Svalbard y Jan Mayen'
} else if (code == 'SZ') {return 'Suazilandia'
} else if (code == 'SE') {return 'Suecia'
} else if (code == 'CH') {return 'Suiza'
} else if (code == 'SY') {return 'Siria'
} else if (code == 'TW') {return 'Taiwán'
} else if (code == 'TJ') {return 'Tayikistán'
} else if (code == 'TZ') {return 'Tanzania'
} else if (code == 'TH') {return 'Tailandia'
} else if (code == 'TL') {return 'Timor Oriental'
} else if (code == 'TG') {return 'Togo'
} else if (code == 'TK') {return 'Tokelau'
} else if (code == 'TO') {return 'Tonga'
} else if (code == 'TT') {return 'Trinidad y Tobago'
} else if (code == 'TN') {return 'Túnez'
} else if (code == 'TR') {return 'Turquía'
} else if (code == 'TM') {return 'Turkmenistán'
} else if (code == 'TC') {return 'Islas Turcas y Caicos'
} else if (code == 'TV') {return 'Tuvalu'
} else if (code == 'UG') {return 'Uganda'
} else if (code == 'UA') {return 'Ucrania'
} else if (code == 'AE') {return 'Emiratos Árabes Unidos'
} else if (code == 'GB') {return 'Reino Unido'
} else if (code == 'US') {return 'Estados Unidos'
} else if (code == 'UY') {return 'Uruguay'
} else if (code == 'UZ') {return 'Uzbekistán'
} else if (code == 'VU') {return 'Vanuatu'
} else if (code == 'VE') {return 'Venezuela'
} else if (code == 'VN') {return 'Vietnam'
} else if (code == 'VG') {return 'Islas Vírgenes Británicas'
} else if (code == 'VI') {return 'Islas Vírgenes de los Estados Unidos'
} else if (code == 'WF') {return 'Wallis y Futuna'
} else if (code == 'YE') {return 'Yemen'
} else if (code == 'ZM') {return 'Zambia'
} else if (code == 'ZW') {return 'Zimbabue'
} else if (code == 'AX') {return 'Åland'
} 
}

export default useCountries;
